---
version: "3.9"

x-podman: &podman
  userns_mode: keep-id
  security_opt:
    - "label=disable"

x-logging: &default-logging
  driver: json-file
  options:
    mode: non-blocking
    max-buffer-size: 4m

volumes:
  ovos_stt_fasterwshiper_cache:
    name: ovos_stt_fasterwshiper_cache
    driver: local
  ovos_stt_fasterwshipe_gradio_cache:
    name: ovos_stt_fasterwshipe_gradio_cache
    driver: local
  ovos_stt_vosk_cache:
    name: ovos_stt_vosk_cache
    driver: local
  ovos_stt_vosk_gradio_cache:
    name: ovos_stt_vosk_gradio_cache
    driver: local
  ovos_stt_chromium_gradio_cache:
    name: ovos_stt_chromium_gradio_cache
    driver: local
  ovos_stt_deepgram_gradio_cache:
    name: ovos_stt_deepgram_gradio_cache
    driver: local

services:
  ovos_stt_fasterwhisper:
    <<: *podman
    container_name: ovos_stt_fasterwhisper
    hostname: ovos_stt_fasterwhisper
    restart: unless-stopped
    image: docker.io/smartgic/ovos-stt-server-fasterwhisper:${VERSION}
    logging: *default-logging
    pull_policy: always
    tty: true
    environment:
      TZ: $TZ
    ports:
      - "8080:8080"
    volumes:
      - ${CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft:ro
      - ovos_stt_fasterwshiper_cache:/home/${OVOS_USER}/.cache
      - ovos_stt_fasterwshipe_gradio_cache:/home/${OVOS_USER}/gradio_cached_examples

  ########################
  # Uncomment this service if you want to use Nvidia CUDA
  # with Faster Whisper Speech-to-Text
  ########################
  # ovos_stt_fasterwhisper:
  #   <<: *podman
  #   container_name: ovos_stt_fasterwhisper
  #   hostname: ovos_stt_fasterwhisper
  #   restart: unless-stopped
  #   image: docker.io/smartgic/ovos-stt-server-fasterwhisper-cuda:${VERSION}
  #   logging: *default-logging
  #   pull_policy: always
  #   tty: true
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities:
  #               - gpu
  #   environment:
  #     TZ: $TZ
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ${CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft:ro
  #     - ovos_stt_fasterwshiper_cache:/home/${OVOS_USER}/.cache
  #     - ovos_stt_fasterwshipe_gradio_cache:/home/${OVOS_USER}/gradio_cached_examples

  ovos_stt_vosk:
    <<: *podman
    container_name: ovos_stt_vosk
    hostname: ovos_stt_vosk
    restart: unless-stopped
    image: docker.io/smartgic/ovos-stt-server-vosk:${VERSION}
    logging: *default-logging
    pull_policy: always
    tty: true
    environment:
      TZ: $TZ
    ports:
      - "8081:8080"
    volumes:
      - ${CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft:ro
      - ovos_stt_vosk_cache:/home/${OVOS_USER}/.local/share/vosk
      - ovos_stt_vosk_gradio_cache:/home/${OVOS_USER}/gradio_cached_examples

  ovos_stt_chromium:
    <<: *podman
    container_name: ovos_stt_chromium
    hostname: ovos_stt_chromium
    restart: unless-stopped
    image: docker.io/smartgic/ovos-stt-server-chromium:${VERSION}
    logging: *default-logging
    pull_policy: always
    tty: true
    environment:
      TZ: $TZ
    ports:
      - "8082:8080"
    volumes:
      - ${CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft:ro
      - ovos_stt_chromium_gradio_cache:/home/${OVOS_USER}/gradio_cached_examples

  ovos_stt_deepgram:
    <<: *podman
    container_name: ovos_stt_deepgram
    hostname: ovos_stt_deepgram
    restart: unless-stopped
    image: docker.io/smartgic/ovos-stt-server-deepgram:${VERSION}
    logging: *default-logging
    pull_policy: always
    tty: true
    environment:
      TZ: $TZ
    ports:
      - "8083:8080"
    volumes:
      - ${CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft:ro
      - ovos_stt_deepgram_gradio_cache:/home/${OVOS_USER}/gradio_cached_examples
